name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@53e8f37565975ec51374a334cb2d1df1f68b47b6 # lint-action branch — bump once grafana/k6-ci#33 merges
    with:
      k6-ci-ref: 53e8f37565975ec51374a334cb2d1df1f68b47b6
      skip-extension-testing: true
