name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@2e841ed1f99228ce33269efa60e300721ba5d683 # lint-action branch — bump once grafana/k6-ci#33 merges
    with:
      k6-ci-ref: 2e841ed1f99228ce33269efa60e300721ba5d683
      skip-extension-testing: true
